#!/bin/bash

echo "Please name your directory :"
read DIR

echo "Please name your codberg repo [$DIR]:"
read REPO
if [ -z "$REPO" ]
then
	REPO=$DIR
fi

echo "Please name your binary file [$DIR]:"
read NAME
if [ -z "$NAME" ]
then
	NAME=$DIR
fi

echo Creating "$NAME" project in $DIR

if [ "${PWD##*/}" != "$DIR" ]
then
	mkdir $DIR
	cd $DIR
fi

cp -r ~/.local/skel/42project/* .

case "$NAME" in
	*.so | *.a)
		echo "*.so"
		sed -i "s|REPLACE_WITH_NAME|lib/$NAME|g" Makefile
		sed -i "s|^\t$(CC) $(LDFLAGS).*$|ar rc $(NAME) $(OBJS)|g"
		;;
	*)
		echo "default"
		sed -i "s|REPLACE_WITH_NAME|bin/$NAME|g" Makefile
		;;
esac

echo 'tea repo create -name "$REPO"'

echo 'Git intialization'
git init

git remote add origin git@codeberg.org:zo/$REPO

echo 'Cloning libft...'
git submodule add git@codeberg.org:zo/libft lib/libft

git add .* *
git commit --message 'Initial commit'
