#!/bin/bash

if [ $# = 1 ]
then
	DIR=$1
else
	echo "Please name your directory :"
	read DIR
fi

echo "Create a remote repository ? Y/n"
read ACCEPT
if [ -n "$ACCEPT" ] && [ $ACCEPT != 'n' ]
then
	echo "Please name your codberg repo [$DIR]:"
	read REPO
	if [ -z "$REPO" ]
	then
		REPO=$DIR
	fi
fi

echo "Please name your binary file [$DIR]:"
read NAME
if [ -z "$NAME" ]
then
	NAME=$DIR
fi

echo Creating "$NAME" project in $DIR

if [ "${PWD##*/}" != "$DIR" ]
then
	mkdir $DIR
	cd $DIR
fi

cp -r ~/.local/skel/42project/* .
cp ~/.local/skel/42project/.gitignore .

case "$NAME" in
	*.so | *.a)
		echo "*.so"
		sed -i "s|REPLACE_WITH_NAME|lib/$NAME|g" Makefile
		sed -i "s|^\t$(CC) $(LDFLAGS).*$|ar rc $(NAME) $(OBJS)|g" Makefile
		;;
	*)
		echo "default"
		sed -i "s|REPLACE_WITH_NAME|bin/$NAME|g" Makefile
		;;
esac

if [ -n "$(which tea)" ] && [ -n "$REPO" ]
then
	tea repo create -name "$REPO"
elif [ -z "$(which tea)" ]
then
	echo "Please install tea (https://gitea.com/gitea/tea) for automated gitea repository creation."
fi

if [ -n "$(which gh)" ] && [ -n "$REPO" ]
then
	gh repo create "$REPO"
elif [ -z "$(which gh)" ]
then
	echo "Please install gh (https://cli.github.com) for automated github repository creation."
fi

rm 42init

echo 'Git intialization'
git init

git remote add origin git@codeberg.org:zo/$REPO

echo 'Cloning libft...'
git submodule add git@codeberg.org:zo/libft lib/libft

git add .* *
git commit --message 'Initial commit'
