name: Code coverage checker
run-name: ${{ gitea.actor }} will ensure your code passes this repository's requirements.
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: archlinux
    steps:
      - run: |
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm clang nodejs make
          #pacman -Sy docker docker-compose llvm 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make stats
      - run: make ${{ gitea.repository}}_coverage.json; mv ${{ gitea.repository }}_coverage.json /mnt/coverage/
