name: Code coverage checker
run-name: ${{ gitea.actor }} will ensure your code passes this repository's requirements.
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: archlinux
    steps:
      - run: |
          ls /mnt/coverage || echo
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm llvm clang nodejs make 
          #pacman -Sy docker docker-compose llvm 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          make stats
          
